### ISSUE TITLE
Error on Click of Reset Button

### ISSUE THREAD

**Issue by LinnZawWin** [Danz-maveRICK/ApplicationInsightsManager#5]
**Describe the bug**

**To Reproduce**
1. Click on 'Load Solutions'
2. Select one of the solutions
3. Click on 'User Existing App Insights Web Resource'
4. Click 'Reset'
5. Error message shows up

**Expected behavior**
Clear the selected checkboxes

**Screenshots**
![](https://i.imgur.com/qzlw2ri.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - XrmToolbox Version: 1.2021.1.44
 - Application Insights Manager Version: 1.2020.4.5

**Additional context**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Items collection cannot be modified when the DataSource property is set.
   at System.Windows.Forms.ComboBox.CheckNoDataSource()
   at Maverick.Azure.ApplicationInsightsManager.MainPluginControl.ResetForm()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by mikekolling1966** [comment]
Yes, it does this to me too
